### ISSUE TITLE
Plugin not working in minepeon MinePeon Pi 0.2.5 pr1

### ISSUE THREAD

**Issue by ghost** [henrylwilliams/minepeon-plugin-MobileMinerApp#4] opened 2014-01-25 13:31 UTC
I have a problem, your plugin is ot working in Version: MinePeon Pi 0.2.5 pr1. I checked to cron commands by runnen the MMAUpdate manually this is the result : 

PHP Notice:  Undefined index: DEVS in /opt/minepeon/http/mma/mobileminerapp.inc.php on line 98
PHP Warning:  Invalid argument supplied for foreach() in /opt/minepeon/http/mma/mobileminerapp.inc.php on line 98
PHP Notice:  Undefined variable: app in /opt/minepeon/http/mma/mobileminerapp.inc.php on line 143

Also the device will not appear in the Machines list from MobileMiner. Please help me

**Comment by henrylwilliams** [comment] 2014-01-27 05:41
The plugin has not been updated for MinePeon 0.2.5, as it wasn't released too long ago, however I'm surprised Neil (MinerForeman) would have changed the structure (again).

I'll try to get to this soon, I haven't even installed 0.2.5 on any of my systems yet, I'll try to get to this within the next few days.

**Comment by henrylwilliams** [comment] 2014-02-12 20:45
I have not been able to reproduce the error on MinePeon 0.2.5 PR2; 

From here out I will not suppose Pre-Release versions, as they are for testing purposes, I will only support actual releases. However from what I can tell now, the plugin seems to be working just fine in MinePeon 0.2.5 PR2.

From the error message you posted, it looks as if the script didn't get a response from the API yet still tried to continue processing it (which is odd), but without being able to reproduce the issue, I'm closing the issue.

**Closed as completed by henrylwilliams** 2014-02-12 20:45 UTC
